- hosts: test_deploy
  become: yes
  tasks:
    - name: install needed packages
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - apt-transport-https
        - curl
        - ca-certificates
        - software-properties-common
        - python-pip

    - name: for sslv3 validate
      shell: pip install --upgrade pip setuptools urllib3 pyOpenSSL ndg-httpsclient pyasn1

    - name: get docker gpg
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: get docker repo
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
        state: present

    - name: install docker
      apt: name={{ item }} update_cache=yes cache_valid_time=3600 state=present
      with_items:
        - docker-ce
        - docker-compose
